spec:
  structures:
    - content_blocks
  label: Contact Us Section
  description: A section for users to contact us with a form and social media links.
  icon: "image"
  tags: ["contact", "form", "social media"]

blueprint:
  title:
  description: 
  insta_image: 
  insta_url: 
  linkedin_image: 
  linkedin_url: 
  submit_btn: 

preview:

