spec:
  structures:
    - content_blocks
  label: Text and Image Section
  description: A section containing a title and an image for the foundation content.
  icon: "image"
  tags: ["text", "foundation", "image"]

blueprint:
  title: 
  image:

preview:

