spec:
  structures:
    - content_blocks
  label: Hero Section
  description: A hero section with a background image, title, highlighted text, and description.
  icon: "image"
  tags: ["hero", "banner", "highlight", "image"]

blueprint:
  title:
  highlight:
  title_suffix:
  description:
  background_image:

preview:
