spec:
  structures:
    - content_blocks
  label: Hero Section
  description: A hero section with a title, highlighted text, and background images.
  icon: "image"
  tags: ["hero", "highlight", "background"]

blueprint:
  title_prefix: 
  highlight: 
  background_img: 
  background_imgTwo: 

preview:

