spec:
  structures:
    - content_blocks
  label: Card Section
  description: A section with a round text and description, followed by multiple cards with images and titles.
  icon: "image"
  tags: ["cards", "foundation", "round", "images"]

blueprint:
  round_text: 
  round_desc:
  cards:
    - image: 
      title: 
    - image: 
      title: 
    - image: 
      title: 

preview:

