spec:
  structures:
    - content_blocks
  label: Hero Section
  description: A hero section with a title, background images, and highlighted text.
  icon: "image"
  tags: ["hero", "background", "highlight"]

blueprint:
  title_prefix: 
  highlight: 
  background_img: 
  background_imgTwo: 

preview:
