spec:
  structures:
    - content_blocks
  label: Hero Section
  description: "Displays the Hero section with title, highlight, and suffix."
  icon: "image"
  tags: ["hero", "title", "highlight"]

blueprint:
  title:
  highlight:
  title_suffix:

preview: