spec:
  structures:
    - content_blocks
  label: Call To Action Section
  description: "Displays a CTA section with multiple cards containing icons, titles, buttons, and hover texts."
  icon: "image"
  tags: ["cta", "button", "hover effect"]

blueprint:
  cards:
    - icon:
      title: "Card Title 1"
      button_text:
      hover_text:
    - icon:
      title: "Card Title 2"
      button_text:
      hover_text:
preview:
