spec:
  structures:
    - content_blocks
  label: Hero Section
  description: A hero section with a title, highlight, and background images.
  icon: "image"
  tags: ["hero", "banner", "image", "highlight"]

blueprint:
  title_prefix:
  highlight: 
  background_img: 
  background_imgTwo: 

preview: